# Generated by Django 4.2 on 2024-12-16 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
        ('product', '0002_remove_productconfiguration_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryconfiguration',
            options={'verbose_name': 'Category Configuration', 'verbose_name_plural': 'Category Configurations'},
        ),
        migrations.AddField(
            model_name='categoryconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='categoryconfiguration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryconfiguration',
            name='category',
            field=models.ForeignKey(help_text='The category this configuration is associated with. Must be a root category.', on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='taxonomy.category'),
        ),
        migrations.AlterField(
            model_name='categoryconfiguration',
            name='input_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('dropdown', 'Dropdown')], help_text='The type of input for this configuration.', max_length=50),
        ),
        migrations.AlterField(
            model_name='categoryconfiguration',
            name='key',
            field=models.CharField(help_text='The configuration key (e.g., RAM, Storage, Color).', max_length=100),
        ),
        migrations.AlterField(
            model_name='categoryconfiguration',
            name='options',
            field=models.TextField(blank=True, help_text='Comma-separated options for dropdown input type (e.g., 4GB,8GB,16GB).', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('notavail', 'ناموجود در ایران'), ('cancelled', 'توقف تولید'), ('tobeavail', 'به زودی موجود'), ('avail', 'موجود در ایران')], default='avail', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='categoryconfiguration',
            unique_together={('category', 'key')},
        ),
    ]
