# Generated by Django 4.2 on 2024-12-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_categoryconfiguration_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='organization',
            new_name='organ',
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('avail', 'موجود در ایران'), ('cancelled', 'توقف تولید'), ('tobeavail', 'به زودی موجود'), ('notavail', 'ناموجود در ایران')], default='avail', max_length=15),
        ),
    ]
