# Generated by Django 5.1.4 on 2024-12-17 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_organization_product_organ_and_more'),
        ('taxonomy', '0003_categoryconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productconfiguration',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='taxonomy.categoryconfiguration'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('cancelled', 'توقف تولید'), ('notavail', 'ناموجود در ایران'), ('tobeavail', 'به زودی موجود'), ('avail', 'موجود در ایران')], default='avail', max_length=15),
        ),
        migrations.DeleteModel(
            name='CategoryConfiguration',
        ),
    ]
