# Generated by Django 5.1.4 on 2024-12-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productconfiguration_configuration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('tobeavail', 'به زودی موجود'), ('notavail', 'ناموجود در ایران'), ('avail', 'موجود در ایران'), ('cancelled', 'توقف تولید')], default='avail', max_length=15),
        ),
    ]
