# Generated by Django 5.1.4 on 2024-12-17 23:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('notavail', 'ناموجود در ایران'), ('tobeavail', 'به زودی موجود'), ('cancelled', 'توقف تولید'), ('avail', 'موجود در ایران')], default='avail', max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
