# Generated by Django 4.2 on 2024-12-14 23:29

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import mobo.storage
import tools.uploader
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_public', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=250)),
                ('title_fa', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('wp_id', models.CharField(blank=True, max_length=12, null=True)),
                ('create_wp_page', models.BooleanField(default=False)),
                ('organ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='organization.organization')),
            ],
            options={
                'abstract': False,
                'unique_together': {('slug', 'organ')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_public', models.BooleanField(default=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('title_fa', models.CharField(blank=True, max_length=256, null=True)),
                ('nickname', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=6, null=True)),
                ('breadcrumbs', models.TextField(blank=True, null=True)),
                ('has_sku', models.BooleanField(default=False)),
                ('has_main', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('svg_icon', models.TextField(blank=True, null=True)),
                ('wp_id', models.CharField(blank=True, max_length=12, null=True)),
                ('create_wp_page', models.BooleanField(default=False)),
                ('multi_config', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, storage=mobo.storage.PublicMediaStorage(), upload_to=tools.uploader.upload_to_category)),
                ('organ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='organization.organization')),
            ],
            options={
                'abstract': False,
                'unique_together': {('slug', 'organ')},
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_public', models.BooleanField(default=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('title_fa', models.CharField(blank=True, max_length=256, null=True)),
                ('nickname', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=6, null=True)),
                ('wp_id', models.CharField(blank=True, max_length=12, null=True)),
                ('create_wp_page', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, storage=mobo.storage.PublicMediaStorage(), upload_to=tools.uploader.upload_to_brand)),
                ('organ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='organization.organization')),
            ],
            options={
                'abstract': False,
                'unique_together': {('slug', 'organ')},
            },
        ),
    ]
