# Generated by Django 5.1.4 on 2024-12-16 21:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100),
        ),
    ]
