# Generated by Django 5.1.4 on 2024-12-17 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_alter_brand_uuid_alter_category_uuid_alter_tag_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The configuration key (e.g., RAM, Storage, Color).', max_length=100)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('dropdown', 'Dropdown')], help_text='The type of input for this configuration.', max_length=50)),
                ('options', models.TextField(blank=True, help_text='Comma-separated options for dropdown input type (e.g., 4GB,8GB,16GB).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(help_text='The category this configuration is associated with. Must be a root category.', on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='taxonomy.category')),
            ],
            options={
                'verbose_name': 'Category Configuration',
                'verbose_name_plural': 'Category Configurations',
                'unique_together': {('category', 'key')},
            },
        ),
    ]
